## macOS system defaults configuration
## Based on https://github.com/geerlingguy/dotfiles/blob/master/.osx

- name: Apply macOS system defaults
  import_tasks: macos_defaults.yml
  tags:
    - macos
    - system
    - never
